<#
  make-public-export.ps1
  Build a clean, publishable copy of this repository (whitelist based), then run a
  safety scan over the result so nothing sensitive can reach GitHub by accident.

  Why whitelist: the working tree contains a live API key (.env), vendor PDF
  manuals, a private licensing server, an extracted third-party app and personal
  files. Copying only what is public is far safer than trusting a blacklist.

  Usage (from the repo root):
    powershell -ExecutionPolicy Bypass -File tools\make-public-export.ps1
    powershell -ExecutionPolicy Bypass -File tools\make-public-export.ps1 -Out D:\tmp\lcode-public
    powershell -ExecutionPolicy Bypass -File tools\make-public-export.ps1 -IncludeLicensingServer -IncludeStage1

  Default output: <parent-of-repo>\lcode-public-export
  Exit code: 0 = export clean, 1 = safety scan found something (fix before pushing).
#>
[CmdletBinding()]
param(
  [string]$Out = '',
  [switch]$Force,
  [switch]$IncludeLicensingServer,   # lcode/server (license + payment backend) - keep PRIVATE by default
  [switch]$IncludeStage1             # embedded_agent_stage1 (legacy MVP) - excluded by default
)

$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $PSScriptRoot
if ($Out -eq '') { $Out = Join-Path (Split-Path -Parent $Root) 'lcode-public-export' }

# Directory names never published (any depth).
# '_internal' = PyInstaller 6 dependency dir (frozen kernel build output, tens to hundreds of MB);
# no source directory ever uses that name. NOTE: keep every comment in this file ASCII-only,
# Windows PowerShell 5.1 reads a BOM-less .ps1 as ANSI and non-ASCII comments break parsing.
$SkipDirNames = @(
  'node_modules', '__pycache__', '.venv', 'venv', 'out', 'dist', '.git', '.tools',
  'ui-ref', 'data', 'outputs', '.pytest_cache', '.mypy_cache', 'htmlcov', '_internal'
)
# File patterns never published (any depth). Last two = frozen kernel binary (win has .exe, mac/linux not)
$SkipFilePatterns = @(
  '*.pem', '*.key', '*.log', '*.db', '*.db-shm', '*.db-wal', '*.npy', '*.pdf',
  '*.pyc', '*.tsbuildinfo', '*.exe', '*.zip', '*.7z', '*.bak', '*.bak-*',
  'lcode-kernel', 'lcode-kernel.*',
  'kb-payload*', 'esp-idf-payload*'
)

$IncludeRootFiles = @('LICENSE', 'NOTICE', 'README.md', '.gitignore', '.gitattributes')
$IncludeDirs = @('lcode', 'docs', 'third_party', 'tools', '.github')
if ($IncludeStage1) { $IncludeDirs += 'embedded_agent_stage1' }

# Repo-relative subtrees that stay private.
$SkipSubPaths = @()
if (-not $IncludeLicensingServer) { $SkipSubPaths += (Join-Path 'lcode' 'server') }
# Build artifacts: PyInstaller work dir / frozen kernel / electron-builder output / planner runtime closure.
# These are rebuilt per machine and must never reach the public repo (measured leak: 145 MB).
$SkipSubPaths += 'lcode\kernel\build'
$SkipSubPaths += 'lcode\kernel\dist'
$SkipSubPaths += 'lcode\desktop\dist'
$SkipSubPaths += 'lcode\desktop\resources\planner\node_modules'
$SkipSubPaths += 'lcode\desktop\resources\planner\dsh-home'
# Self-contained planner runtime (route B) is built by tools/planner-bundle: apps/ holds the
# built DSH CLI, home/ the DSH_HOME skeleton and manifest.json the bundle descriptor. All of
# it is a build artifact produced from DSH sources + lcode/planner, so it never ships in git.
$SkipSubPaths += 'lcode\desktop\resources\planner\apps'
$SkipSubPaths += 'lcode\desktop\resources\planner\home'
$SkipSubPaths += 'lcode\desktop\resources\esp-idf'
# Installers / payloads / component archives must never be committed: GitHub rejects files
# over 100 MB and the repo would balloon. They belong to GitHub Releases (see
# tools/publish-release.ps1). *.exe and *.zip are already in $SkipFilePatterns; these
# subtrees cover the build output and component dirs.
$SkipSubPaths += 'lcode\desktop\dist'
$SkipSubPaths += 'lcode\desktop\resources\kb'

# Repo-relative single files that stay private: internal release/close-source playbook
# (contains private-repo paths, archived payment-channel notes and machine-specific paths).
#
# NOTE: the file name is Chinese and this script must stay pure ASCII - Windows PowerShell 5.1
# reads a BOM-less .ps1 as ANSI and would corrupt a literal. Build the name from code points.
$InternalDocNames = @(
  (-join [char[]]@(0x5F00, 0x6E90, 0x53D1, 0x5E03, 0x6E05, 0x5355)) + '.md'   # release checklist
)
$SkipRelFiles = @()
foreach ($n in $InternalDocNames) { $SkipRelFiles += (Join-Path 'docs' $n) }
# Planner bundle descriptor: build artifact (version/stamp), regenerated by tools/planner-bundle.
$SkipRelFiles += 'lcode\desktop\resources\planner\manifest.json'

function Test-SkipDir([string]$name) { return ($SkipDirNames -contains $name) }

function Test-SkipRelFile([string]$relFromRoot) {
  return ($SkipRelFiles -contains ($relFromRoot -replace '/', '\'))
}

function Test-SkipFile([string]$name) {
  if ($name -eq '.env.example') { return $false }   # the example stays; the real .env never does
  if ($name -eq '.env' -or $name -like '.env.*') { return $true }
  foreach ($p in $SkipFilePatterns) { if ($name -like $p) { return $true } }
  return $false
}

function Copy-Whitelisted([string]$srcAbs, [string]$dstAbs, [string]$relFromRoot) {
  if ($SkipSubPaths -contains ($relFromRoot -replace '/', '\')) {
    Write-Host ("  skip private subtree: {0}" -f $relFromRoot) -ForegroundColor DarkYellow
    return
  }
  if (Test-Path -LiteralPath $srcAbs -PathType Container) {
    if (Test-SkipDir (Split-Path $srcAbs -Leaf)) { return }
    New-Item -ItemType Directory -Force -Path $dstAbs | Out-Null
    foreach ($f in Get-ChildItem -LiteralPath $srcAbs -File -Force) {
      if (Test-SkipFile $f.Name) { continue }
      if (Test-SkipRelFile (Join-Path $relFromRoot $f.Name)) {
        Write-Host ("  skip internal file: {0}" -f (Join-Path $relFromRoot $f.Name)) -ForegroundColor DarkYellow
        continue
      }
      Copy-Item -LiteralPath $f.FullName -Destination (Join-Path $dstAbs $f.Name) -Force
    }
    foreach ($d in Get-ChildItem -LiteralPath $srcAbs -Directory -Force) {
      Copy-Whitelisted $d.FullName (Join-Path $dstAbs $d.Name) (Join-Path $relFromRoot $d.Name)
    }
  }
}

Write-Host "repo root  : $Root"
Write-Host "export out : $Out"
# Preserve the export dir's own .git: removing it would silently destroy the repo history once
# this directory is a real clone (measured hazard: a first commit made here was wiped by the
# next re-export). The source repo's .git is never copied - only the target's own is kept.
$gitDir = Join-Path $Out '.git'
$gitTemp = $null
if ((Test-Path $gitDir) -and (-not $Force)) {
  $gitTemp = Join-Path ([System.IO.Path]::GetTempPath()) ('lcode-export-git-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
  Move-Item -LiteralPath $gitDir -Destination $gitTemp -Force
  Write-Host '  preserving existing .git (repo history kept)' -ForegroundColor DarkYellow
}
if (Test-Path $Out) {
  if (-not $Force) { Remove-Item -LiteralPath $Out -Recurse -Force }
  else { Write-Host '(-Force: keeping existing out dir, files will be overwritten)' -ForegroundColor Yellow }
}
New-Item -ItemType Directory -Force -Path $Out | Out-Null
if ($gitTemp) {
  Move-Item -LiteralPath $gitTemp -Destination $gitDir -Force
  Write-Host '  .git restored' -ForegroundColor DarkYellow
}

foreach ($f in $IncludeRootFiles) {
  $p = Join-Path $Root $f
  if (Test-Path -LiteralPath $p) { Copy-Item -LiteralPath $p -Destination (Join-Path $Out $f) -Force }
}
foreach ($f in Get-ChildItem -LiteralPath $Root -Filter '*.bat' -File) {
  Copy-Item -LiteralPath $f.FullName -Destination (Join-Path $Out $f.Name) -Force
}
foreach ($d in $IncludeDirs) {
  $p = Join-Path $Root $d
  if (Test-Path -LiteralPath $p) { Copy-Whitelisted $p (Join-Path $Out $d) $d }
}

# ---------------- safety scan ----------------
Write-Host ''
Write-Host '--- safety scan ---' -ForegroundColor Cyan
$findings = @()
# Hard guarantee: private subtrees must not exist in the export at all.
foreach ($s in $SkipSubPaths) {
  if (Test-Path -LiteralPath (Join-Path $Out $s)) { $findings += "PRIVATE SUBTREE LEAKED: $s" }
}
foreach ($f in Get-ChildItem -LiteralPath $Out -Recurse -File -Force) {
  $rel = $f.FullName.Substring($Out.Length).TrimStart('\')
  if (($f.Name -eq '.env' -or $f.Name -like '.env.*') -and $f.Name -ne '.env.example') { $findings += "ENV FILE: $rel" }
  foreach ($p in @('*.pem', '*.key', '*.db', '*.db-shm', '*.db-wal', '*.npy', '*.pdf')) {
    if ($f.Name -like $p) { $findings += "SENSITIVE FILE: $rel" }
  }
  if ($rel -match 'ui-ref|workbuddy') { $findings += "THIRD-PARTY APP: $rel" }
  # Size tripwire: a source repo must not contain any file >20 MB
  # (build outputs / models / vector stores / installers all fall in that class -> something leaked).
  if ($f.Length -gt 20MB) { $findings += ("LARGE FILE (>20MB): {0} ({1:N1} MB)" -f $rel, ($f.Length / 1MB)) }
  if ($f.Extension -in @('.ts', '.tsx', '.js', '.json', '.py', '.md', '.txt', '.yml', '.yaml', '.ps1', '.bat', '.example') -and $f.Length -lt 2MB) {
    $text = Get-Content -LiteralPath $f.FullName -Raw -ErrorAction SilentlyContinue
    if ($text -match 'sk-[A-Za-z0-9]{20,}') { $findings += "HARDCODED API KEY: $rel" }
    if ($text -match 'BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY') { $findings += "PRIVATE KEY BLOCK: $rel" }
  }
}

$files = Get-ChildItem -LiteralPath $Out -Recurse -File -Force
$sum = ($files | Measure-Object -Property Length -Sum).Sum
Write-Host ("files: {0}   size: {1} MB" -f $files.Count, [math]::Round(($sum / 1MB), 2))
Get-ChildItem -LiteralPath $Out -Force | Sort-Object Name | ForEach-Object {
  $n = if ($_.PSIsContainer) { (Get-ChildItem -LiteralPath $_.FullName -Recurse -File -Force -ErrorAction SilentlyContinue).Count } else { 1 }
  Write-Host ("  {0,-24} {1,6} files" -f $_.Name, $n)
}
Write-Host ''
if ($findings.Count -eq 0) {
  Write-Host 'OK: no .env, private keys, vendor PDFs, third-party app dumps or hardcoded API keys.' -ForegroundColor Green
  Write-Host 'Next: git init inside the export dir, review "git status", push to a PRIVATE repo first.' -ForegroundColor Green
  exit 0
}
Write-Host 'FOUND ISSUES (do not push before fixing):' -ForegroundColor Red
$findings | Sort-Object -Unique | ForEach-Object { Write-Host ("  - {0}" -f $_) -ForegroundColor Red }
exit 1
